---
? ''
: - ttl: 600
    type: ALIAS
    value: jekyll.github.io.
  - ttl: 600
    type: MX
    values:
    - exchange: mxa.mailgun.org.
      preference: 10
    - exchange: mxb.mailgun.org.
      preference: 20
  - ttl: 600
    type: TXT
    value: v=spf1 include:mailgun.org include:_hostedspf.discourse.org ~all
_github-challenge-jekyll:
  ttl: 600
  type: TXT
  value: de13dd597c
dashboard:
  ttl: 600
  type: CNAME
  value: jekyll-dashboard.herokuapp.com.
discourse._domainkey:
  ttl: 600
  type: TXT
  value: v=DKIM1\; k=rsa\; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCojtk3fqF69pT6SZcIwoYzjQfdOBTFK7AOyxEGBwHLZ+xqwQQlVgfL6xFZ7FhCYAczkGTCjdChX/qf6dg4LrtXrb+apymj9WpLOwPir6P5Mv9FH3t3BgrQeyyCLhAHqDrUk+kU3B2z1uva3oWw3qN9MLZaX8HjR13w9ywVEgzjpQIDAQAB
email:
  ttl: 600
  type: CNAME
  value: mailgun.org.
email.talk:
  ttl: 600
  type: CNAME
  value: mailgun.org.
import:
  ttl: 600
  type: CNAME
  value: jekyll.github.io.
pic._domainkey:
  ttl: 600
  type: TXT
  value: k=rsa\; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCeXUl1vOMvfMJWYoNylrDLYOeSNadGsxPJEgc0iYgAVbKhxZXBbiNxlt6lhziENYchiUgPNC2JVK9izmXVLo5uizgBVWaYrLOLFiy4Kb4ewL8uEl2cBlWsuFSmOa+6zx4dErmGXLf4hie0blQ/g1rgg11ll34+1XpGYTjsIDXbHwIDAQAB
talk:
- ttl: 600
  type: A
  value: 216.218.240.80
- ttl: 600
  type: TXT
  value: v=spf1 include:mailgun.org ~all
teams:
  ttl: 600
  type: CNAME
  value: teams.jekyllrb.com.herokudns.com.
www:
  ttl: 600
  type: CNAME
  value: jekyll.github.io.
www.teams:
  ttl: 600
  type: CNAME
  value: teams.jekyllrb.com.herokudns.com.
