on:
  push:
    branches:
      - master
      - github-actions

name: Deploy on push
jobs:
  deployOnPush:
    name: octodns sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: octodns sync
      uses: docker://parkr/octodns:e23579686537136b1c2fdd7f52dba430e278712b
      env:
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
      with:
        args: octodns-sync --config-file ./config/production.yaml --doit
