on: push
name: Test on push
jobs:
  octodnsTest:
    name: octodns test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: octodns test
      uses: docker://parkr/octodns:e23579686537136b1c2fdd7f52dba430e278712b
      env:
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
      with:
        args: octodns-sync --config-file ./config/production.yaml
